from distutils.core import setup

setup(name='web_pet_project',
      version='1.0',
      description='PET project for automation practice',
      author='Ivan Demianchuk',
      url='http://the-internet.herokuapp.com/',
      packages=['pytest'],
      install_requires=['allure-pytest',
                        'allure-python-commons',
                        'attrs',
                        'certifi',
                        'cffi',
                        'colorama',
                        'exceptiongroup',
                        'h11',
                        'idna',
                        'iniconfig',
                        'outcome',
                        'packaging',
                        'pip',
                        'pluggy',
                        'pycparser',
                        'PySocks',
                        'pytest',
                        'selenium',
                        'setuptools',
                        'six',
                        'sniffio',
                        'sortedcontainers',
                        'tomli',
                        'trio',
                        'trio-websocket',
                        'urllib3',
                        'wheel',
                        'wsproto',
                        ])
